core/urls.py
from django.urls import path, include
from core.views import ContactView, DetailNew, GalleryView, ContributorsView, NewsView

app_name = 'core'

urlpatterns = [
    path('gallery/', GalleryView.as_view(), name='gallery'),
    path('contributors/', ContributorsView.as_view(), name='contributors'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('news/', NewsView.as_view(), name='news'),
    path('news/<str:canonical_name>-<int:id>/',
         DetailNew.as_view(),
         name='post'),
]

football_competion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('tournoi.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

tournoi/urls.py
from django.urls import path
from tournoi.views import IndexView, MatchView, TeamView

app_name = 'tournoi'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('match/', MatchView.as_view(), name='match'),
    path('teams/', TeamView.as_view(), name='team'),
]

core/models.py
from django.db import models
from django_tuieditor.models import MarkdownField
from tournoi.models import Edition


class ContactInfo(models.Model):
    '''Manages the contact form/page'''
    name = models.CharField(
        max_length=150,
        null=False,
        blank=False,
        error_messages={'required': ("Veuillez entrer votre nom et prénom.")})
    email = models.EmailField(
        null=True,
        blank=True,
        error_messages={'required': ("Veuillez entrer votre adresse email.")})
    phone = models.CharField(max_length=9,
                             null=False,
                             blank=False,
                             error_messages={
                                 'required':
                                 ("Veuillez entrer votre numéro de téléphone.")
                             })
    subject = models.CharField(
        max_length=100,
        error_messages={
            'required': ("Veuillez entrer le titre de votre message.")
        })
    message = models.TextField(
        null=False,
        blank=False,
        error_messages={'required': ("Veuillez entrer votre message.")})

    def __str__(self):
        return self.name + ' ' + self.subject


class Author(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='author',
                              default='author/avatar.png',
                              null=True,
                              blank=True)
    description = MarkdownField(max_length=150, null=False, blank=False)

    def __str__(self) -> str:
        return self.name


class News(models.Model):
    image = models.ImageField(
        upload_to='actualites/',
        default="news_placeholder.jpg",
    )
    title = models.CharField(
        max_length=200,
        null=False,
        blank=False,
    )
    description = MarkdownField(
        null=False,
        blank=False,
    )
    edition = models.ForeignKey(Edition, models.CASCADE)
    add_on = models.DateField(auto_now=True)
    author = models.ForeignKey(Author, models.CASCADE)

    def __str__(self):
        return self.title


class Gallery(models.Model):
    title = models.CharField(max_length=300, blank=True, null=True)
    edition = models.ForeignKey(Edition,
                                models.CASCADE,
                                related_name='gallery',
                                null=True,
                                blank=True)

    def __str__(self) -> str:
        return self.title


class GalleryImage(models.Model):
    gallery = models.ForeignKey(Gallery, models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='galleries/', null=False)
    alt = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self) -> str:
        return f'photo de {self.gallery.title}'


class Contributor(models.Model):
    image = models.ImageField(upload_to='contributors/', null=False)
    name = models.CharField(max_length=300, blank=True, null=True)
    title = models.CharField(max_length=300, blank=True, null=True)
    website = models.URLField(max_length=300, )
    twitter = models.URLField(max_length=300, )
    github = models.URLField(max_length=300, )
    description = models.TextField()

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from .models import ContactInfo
from django.forms.widgets import CheckboxInput, EmailInput, FileInput, NumberInput, PasswordInput, Select, TextInput, Textarea


# Create your forms below.
class ContactForm(forms.ModelForm):
    # Meta data
    class Meta:
        model  = ContactInfo

        # Form fields
        fields = [
            'name',
            'email',
            'phone',
            'subject',
            'message'
        ]

        # Definition of widgets
        widgets = {
            'name': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Nom et Prénom',
                }
            ),

            'email': EmailInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Your email address',
                }
            ),

            'phone': TextInput(
                attrs={
                    'class': 'form-control w-75',
                    'placeholder': 'Téléphone (Ex. 699887755)',
                }
            ),

            'subject': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Message Subject...',
                }
            ),

            'message': Textarea(
                attrs={
                    'cols': '30',
                    'rows': '10',
                    'class': 'form-control',
                    'placeholder': 'Ecrivez votre message...',
                }
            ),
        }

core/views.py
from pipes import Template
from pprint import pp, pprint
from django.shortcuts import get_object_or_404, redirect, render, HttpResponse
from django.db.models import Count
from django.views import View
from core.models import Contributor, GalleryImage, News, Gallery
from django.views.generic import ListView
from .forms import ContactForm
from django.core.mail.message import BadHeaderError
from django.core.mail import send_mail
from django.contrib import messages
from django.utils.html import format_html
from tournoi.models import Edition
from django.views.generic import TemplateView


class ContactView(View):
    template_name = 'core/contact.html'
    form_class = ContactForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']

            # Additional fields
            messsage = f"\n\nNouveau message sur coupe.comsas.club : Emetteur: {name}\n\nAdresse: {email} Message:{message}"
            subjectEmail = f'{subject}From <{email}>'

            # Uncomment this later to send email to required address
            # try:
            #     send_mail(
            #         subjectEmail,  #subject
            #         message,  #message
            #         email,  #from email
            #             ,  #to email
            #     )
            # except BadHeaderError:
            #     message.error(request, 'Désolé, Nous avons rencontré un problème lors de l\'envoi de votre reponse. Veuillez réessayer plustard.')

            # Test if form data was saved and output corresponding flash message to confirm message placement or not.
            try:
                form.save()
                message_out_success = format_html(
                    # f'Thanks for contacting us, <strong> {name} </strong> ! Your message has been sent successfully. You will be email a copy at <strong> {email} </strong> !'
                    f'Votre message a été envoyé avec succès. Merci de nous avoir contacté,'
                )
                messages.success(request, message_out_success)
            except:
                messages.error(request, 'Désolé, Nous avons rencontré un problème lors de l\'envoi de votre reponse. Veuillez réessayer plustard.')

            # Redidrect to the same page with message output.
            return redirect('core:contact')
        else:
            return render(request, self.template_name, {'form': form})


class GalleryView(View):
    template_name = "core/gallery.html"

    def get(self, request, *args, **kwargs):
        last_edition = Edition.objects.filter(
            status='programmed').order_by('-end_date').first()
        last_edition_gallery = Gallery.objects.filter(
            edition=last_edition.id).first()
        last_edition_images = GalleryImage.objects.filter(
            gallery=last_edition_gallery.id)
        context = {
            'last_edition_images': last_edition_images,
        }
        return render(request, self.template_name, context)


class ContributorsView(ListView):
    template_name = "core/contributors.html"
    queryset = Contributor.objects.all()


class NewsView(View):
    template_name = "core/blog.html"

    def get(self, request, *args, **kwargs):
        queryset = News.objects.filter(edition__status='active')
        context = {'news': queryset}
        return render(request, self.template_name, context)


class DetailNew(View):
    template_name = "core/single.html"

    def get(self, request, *args, **kwargs):
        new = get_object_or_404(News, id=self.kwargs['id'])
        news = News.objects.filter(edition__status='active')
        context = {'new': new, 'news': news}
        return render(request, self.template_name, context)

core/templates/core/blog.html
{% extends 'core/main.html' %}
{% load static %}
{% load i18n %}
{% load gfm %}

{% comment %} Title of the page {% endcomment %}
{% block title %}
  {% translate "Blog Posts" %}
{% endblock title %}

{% comment %} Body of the page {% endcomment %}
{% block body %}
<div class="hero overlay" style="background-image: url('../../static/images/bg_4.jpg');">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-10 mx-auto text-center">
          <h1 class="text-white text-capitalize"><span style="color: transparent; -webkit-text-stroke-width: 2px; -webkit-text-stroke-color: #ee1e46;">{% trans "Blog Posts" %}</span> {% translate "| Actualités" %}</h1>
          <p>
              {% translate "Ne vous inquietez plus! Désormais toute l'actualité concernant la coupe du département d'Inforamtique est accessible via notre blog d'information, où nous posterons régulierement durant le déroulement du dit championnat." %}
          </p>
        </div>
      </div>
    </div>
  </div>

  
  
  <div class="container site-section">
    <div class="row">
      <div class="col-6 title-section">
        <h2 class="heading">{% translate "Les plus récents" %}</h2>
      </div>
    </div>
    <div class="row">
     {% for new in news %}
      <div class="col-lg-4 mb-4">
        <div class="custom-media d-block">
          <div style="height: 60vh;">
            <a href="{% url 'core:post' new.title|slugify new.id%}">
              <img src="{{new.image.url}}" alt="Image" class="img-fluid" style="object-fit: cover; height: 100%; width: 100%;">
            </a>
          </div>
          <div class="text">
            <span class="meta">{{new.add_on|date:"D d M Y"}}</span> 
            <h3 class="mb-4"><a href="{% url 'core:post' new.title|slugify new.id%}">{{new.title|title}}</a></h3>
            <p>{{new.description|gfm|slice:'165'}}...</p>
            <p><a href="{% url 'core:post' new.title|slugify new.id%}">Read more</a></p>
          </div>
        </div>
      </div>
      {% endfor %} 
    </div>

    <div class="row justify-content-center">
      <div class="col-lg-7 text-center">
        <div class="custom-pagination">
          <a href="#">1</a>
          <span>2</span>
          <a href="#">3</a>
          <a href="#">4</a>
          <a href="#">5</a>
        </div>
      </div>
    </div>
  </div>
{% endblock body %}

core/templates/core/contributors.html
{% extends 'core/main.html' %}
{% load static %}
{% load i18n %}
{% load gfm %}

<!-- Block Title -->
{% block title %}
{% translate "Contributeurs" %}
{% endblock title %}

<!-- Page Body -->
{% block body %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-center align-items-center" style="background-image: url('../../static/images/gallery-bg.webp');">
    <div class="hero-container" data-aos="fade-in">
      <h1><span style="color: transparent; -webkit-text-stroke-width: 2px; -webkit-text-stroke-color: #ee1e46;">#</span> La T<span style="color: #ee1e46; border-bottom: 5px solid #ee1e46;">e</span>ch <span style="color: #ee1e46;"><\</span>Team<span style="color: #ee1e46;">></span></h1><span style="color: #ee1e46;"></span>
      <br>
      <small>
          {% translate "Nous l'avons essayé, et nous l'avons réalisé." %}
        </small>
      <br>
    </div>
</section>
<!-- End Hero -->

<br>
<br>

<!-- Contributor Section Begin -->
<section class="speaker-section spad">
    <div class="container">
        <div class="row">
            {% for person in contributor_list %}
            <div class="col-md-6">
                <div class="speaker-item">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="si-pic">
                                <img src=" {{person.image.url}} " alt="{{person.name}}">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="si-text text-capitalize">
                                <div class="si-title">
                                    <h4>{{person.name}}</h4>
                                    <span class="text-capitalize">
                                        {{person.title}}
                                    </span>
                                </div>
                                <div class="si-social">
                                    <a href="{{person.website}}"><i class="bi bi-globe2"></i></a>
                                    <a href="{{person.twitter}}"><i class="bi bi-twitter"></i></a>
                                    <a href="{{person.github}}"><i class="bi bi-github"></i></a>
                                </div>
                                <p>
                                    {{person.description|gfm}} 
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Contributor Section End -->
    
{% endblock body %}

core/templates/core/index.html
{% extends 'core/main.html' %}

<!-- load some element -->
{% load static %}
{% load i18n %}
{% load gfm%}

<!-- Title of home the page-->
{% block title %}
 {% translate "Accueil" %}
{% endblock title %}


<!-- Body of the home page-->
{% block body %}
<div class="hero overlay" style="background-image: url('../../static/images/bg_3.jpg');">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-5 ml-auto mt-5 mt-lg-0 pt-5 pt-lg-0">
        <h1 class="text-white">Coupe du Département <span style="color: #ee1e46;">Info</span><span style="color: transparent; -webkit-text-stroke-width: 2px; -webkit-text-stroke-color: #fff;">rmatique</span></h1>
        <p>
          {% translate "Ce n'est pas toujours une affaire de machines. On s'y connait aussi au foot." %}
        </p>
        <p>
         Prochain match dans ...
        </p>
        <div id="dateCount" style="display: none;">{{next_match.match.date_to_play|date:"SHORT_DATE_FORMAT"}}</div>
        <div id="date-countdown"></div>
        <p>
         
        </p>
        <p>
          <a href="#latest-news" class="btn btn-primary py-3 px-4 mr-3">{% translate "Découverte" %}</a>
          <a href="{% url 'tournoi:match' %}" class="btn btn-outline-primary py-3 px-4 mr-3 more light" style="border: 3px solid #ee1e46">{% translate "Statistiques" %}</a>
        </p>  
      </div>
    </div>
  </div>
</div>



<div class="container">
  

  <div class="row">
    <div class="col-lg-12">
      {% if last_match %}
      <div class="d-flex team-vs">
        <span class="score">{{ last_match.match.goal_team1}} : {{ last_match.match.goal_team2 }}</span>
        <div class="team-1 w-50">
          <div class="team-details w-100 text-center">
            <img src=" {{last_match.team1.logo.url}} " alt="Image" class="img-fluid">
            <h3 class="text-uppercase">{{last_match.team1.name}} {% if last_match.match.winner == last_match.team1 %} <small style="color: #ee1e46; font-weight: 600;">({% translate "victoire" %})</small> <i class="bi bi-hand-thumbs-up-fill"></i>
              {% elif  last_match.macth.winner == last_match.team2 %}<small style="color: #000; font-weight: 600;">({% translate "défaite" %})</small>{% endif %} </h3>
            <ul class="list-unstyled">

            </ul>
          </div>
        </div>
        <div class="team-2 w-50">
          <div class="team-details w-100 text-center">
            <img src=" {{last_match.team2.logo.url}} " alt="Image" class="img-fluid">
            <h3 class="text-uppercase">{{last_match.team2.name}} {% if last.match.winner == last_match.team2 %} <small style="color: #ee1e46; font-weight: 600;">({% translate "victoire" %})</small> <i class="bi bi-hand-thumbs-up-fill"></i>
              {% elif  last_match.match.winner == last_match.team1 %}<small style="color: #000; font-weight: 600;">({% translate "défaite" %})</small>{% endif %}</h3>
          </div>
        </div>
      </div>
    {% endif %}
    </div>
  </div>
</div>


<div class="latest-news">
  <div class="container">
    <div class="row">
      <div class="col-12 title-section">
        <h2 class="heading" id="latest-news">{% translate "Actualités sur le championnat" %}</h2>
      </div>
    </div>
    <div class="row no-gutters">

      {% for new in news %}
      <div class="col-lg-4 mb-4">
        <div class="custom-media d-block">
          <div style="height: 60vh;">
            <a href="{% url 'core:post' new.title|slugify new.id%}">
              <img src="{{new.image.url}}" alt="Image" class="img-fluid" style="object-fit: cover; height: 100%; width: 100%;">
            </a>
          </div>
          <div class="text">
            <span class="meta">{{new.add_on|date:"D d M Y"}}</span>
            <h3 class="mb-4"><a href="{% url 'core:post' new.title|slugify new.id%}">{{new.title|title}}</a></h3>
            <p>{{new.description|gfm|slice:'165'}}...</p>
            <p><a href="{% url 'core:post' new.title|slugify new.id%}">Read more</a></p>
          </div>
        </div>
      </div>
      {% endfor %} 
    </div>

    </div>

  </div>
</div>

<div class="site-section bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="col-12 title-section">
          <h2 class="heading" id="latest-news">{% translate "Poule A" %}</h2>
        </div>
        <div class="widget-next-match">
          <table class="table custom-table">
            <thead>
              <tr>
                {% comment %} 
                  Normalement la traduction en anglais devrait aussi changer les lettres ci dessous comme suit.
                  Fr ------ En
                  R  =====> R
                  J  =====> P
                  V  =====> W
                  N  =====> D
                  D  =====> L
                  PTS  =====> PTS
                {% endcomment %}

                <th>R</th>
                <th>{% translate "Équipe" %}</th>
                
                <th>V</th>
                <th>N</th>
                <th>D</th>
                <th>PTS</th>
              </tr>
            </thead>
            <tbody>
              {% for elt in classement_A %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td><strong class="text-white">{{elt.abreviation}}</strong></td>
                  
                  <td>{{elt.victory}}</td>
                  <td>{{elt.null}}</td>
                  <td>{{elt.defeat}}</td>
                  
                  <td>{{elt.points}}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="col-12 title-section">
          <h2 class="heading" id="latest-news">{% translate "Poule B" %}</h2>
        </div>
        <div class="widget-next-match">
          <table class="table custom-table">
            <thead>
              <tr>
                {% comment %} 
                  Normalement la traduction en anglais devrait aussi changer les lettres ci dessous comme suit.
                  Fr ------ En
                  R  =====> R
                  J  =====> P
                  V  =====> W
                  N  =====> D
                  D  =====> L
                  PTS  =====> PTS
                {% endcomment %}

                <th>R</th>
                <th>{% translate "Équipe" %}</th>
                
                <th>V</th>
                <th>N</th>
                <th>D</th>
                <th>PTS</th>
              </tr>
            </thead>
            <tbody>
              {% for elt in classement_B %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td><strong class="text-white">{{elt.abreviation}}</strong></td>
                  
                  <td>{{elt.victory}}</td>
                  <td>{{elt.null}}</td>
                  <td>{{elt.defeat}}</td>
                  <td>{{elt.points}}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-lg-12">
        <div class="widget-next-match">
          <div class="widget-title">
            <h3 class="text-capitalize">{% translate "Prochain Match" %}</h3>
          </div>
          <div class="widget-body mb-3">
            <div class="widget-vs">
              <div class="d-flex align-items-center justify-content-around justify-content-between w-100">
                <div class="team-1 text-center">
                  <img src=" {{next_match.team1.logo.url}} " alt="{{next_match.team1.name}}">
                  <h3 class="text-capitalize">{{next_match.team1.name}}</h3>
                </div>
                <div>
                  <span class="vs"><span>VS</span></span>
                </div>
                <div class="team-2 text-center">
                  <img src=" {{next_match.team2.logo.url}} " alt="{{next_match.team2.name}}">
                  <h3 class="text-capitalize">{{next_match.team2.name}}</h3>
                </div>
              </div>
            </div>
          </div>
  
          <div class="text-center widget-vs-contents mb-4">
            <h4 class="text-capitalize">{{next_match.match.title|title|default_if_none:'Coupe du département'}}</h4>
            <p class="mb-5">
              <span class="d-block">{{ next_match.match.date_to_play }}</span>
              <!-- span class="d-block">15:30 (GMT+1)</span   !-->
              <strong class="text-primary">{{next_match.match.stade_name|title}}</strong>
            </p>
  
            <small>{% translate "Prochain match dans:" %}</small>
            <div id="dateCount2" style="display: none;">{{next_match.match.date_to_play|date:"SHORT_DATE_FORMAT"}}</div>
            <div id="date-countdown2" class="pb-1"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> <!-- .site-section -->

<div class="site-section">
  <div class="container">
    <div class="row">
      <div class="col-6 title-section">
        <h2 class="heading text-capitalize">{% translate "Meilleur Joueurs" %}</h2>
      </div>
      <div class="col-6 text-right">
        <div class="custom-nav">
        <a href="#" class="js-custom-prev-v2"><span class="icon-keyboard_arrow_left"></span></a>
        <span></span>
        <a href="#" class="js-custom-next-v2"><span class="icon-keyboard_arrow_right"></span></a>
        </div>
      </div>
    </div>


    <div class="owl-4-slider owl-carousel" id='top_players'>
      {% for player in top_players %}
        <div class="item">
          <div class="video-media">
            <img src=" {{player.photo.url}} " alt="Image" class="img-fluid">
            <a href="{{player.photo.url}}" class="d-flex play-button align-items-center" data-fancybox>
              <span class="icon mr-3">
                <span >{{player.dossard}}</span>
              </span>
              <div class="caption">
                <h3 class="m-0">{{player.name|title}}</h3>
              </div>
            </a>
          </div>
        </div>
       {% endfor %}
      

    </div>

  </div>
</div>

{% comment %} <div class="container site-section">
  <div class="row">
    <div class="col-6 title-section">
      <h2 class="heading">Blog</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6">
      <div class="custom-media d-flex">
        <div class="img mr-4">
          <img src=" {% static 'images/img_1.jpg' %} " alt="Image" class="img-fluid">
        </div>
        <div class="text">
          <span class="meta">May 20, 2020</span>
          <h3 class="mb-4"><a href="#">Romolu to stay at Real Nadrid?</a></h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus deserunt saepe tempora dolorem.</p>
          <p><a href="#">Read more</a></p>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="custom-media d-flex">
        <div class="img mr-4">
          <img src=" {% static 'images/img_3.jpg' %} " alt="Image" class="img-fluid">
        </div>
        <div class="text">
          <span class="meta">May 20, 2020</span>
          <h3 class="mb-4"><a href="#">Romolu to stay at Real Nadrid?</a></h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus deserunt saepe tempora dolorem.</p>
          <p><a href="#">Read more</a></p>
        </div>
      </div>
    </div>
  </div>
</div> {% endcomment %}

{% endblock body %}

core/templates/core/single.html
{% extends 'core/main.html' %}
{% load static %}
{% load i18n %}
{% load gfm %}

<!-- Page Title-->
{% block title %} {% translate "Article" %}
{% endblock title %}

{% block body %}
<div class="hero overlay" style="background-image: url('../../static/images/bg_5.jpg');">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-9 mx-auto text-center">
        <h1 class="text-white">{% translate "Quoi de neuf" %} <span style="color: #ee1e46;">!</span></h1>
        <p>{% translate "Nous donnons le meilleur de nous pour vous offrir l'information de qualité." %}</p>
      </div>
    </div>
  </div>
</div>


<div class="site-section first-section">
  <div class="container">
    <div class="row">
      <div class="col-md-8 blog-content">
        <p class="lead" id="content1">
          {{new.title|upper}}
        </p>


        <p>
          <a href="{{new.image.url}}" title="Cliquez pour voir l'image">
            <img src="{{new.image.url}}" alt="Image" class="img-fluid">
          </a>
          
        </p>

        {{new.description|gfm}}
        <hr style="background-color: rgba(255, 255, 255, 0.3);">
        <div class="bottom-left" style="display: flex;">
          <div class="author-img">
            <img src="{{new.author.image.url}}" alt="" >
          </div>
          <div class="author-text">
            <h5>{{new.author.name}}</h5>
            <small class="">{{new.author.description}}</small>
          </div>
        </div>
      </div>
      
      <div class="col-md-4 sidebar">
        <!-- <div class="sidebar-box">
          <form action="#" class="search-form">
            <div class="form-group">
              <span class="icon fa fa-search"></span>
              <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
            </div>
          </form>
        </div> -->

        <!-- Cette section sera pour afficher les titres des differentes sections a venir. -->
        <h2 class="font-weight-bold">{% translate "Plus d'actualités" %}</h2>
        {% for new  in news %}
          <ol>
            <li><a href="{% url 'core:post' new.title|slugify new.id%}">{{new.title|title}}</a></li>
          </ol>
        {% endfor %}
        <div style="height: 10vh;"></div>
        <!--div class="sidebar-box">
          <img src=" {% static 'images/logo_comsas.png' %} " alt="Image placeholder" class="img-fluid mb-4" style="width: 50%;">
          <br>
          <h3 class="text-uppercase">{% translate "A Propos Des Auteurs" %}</h3>
          <p>{% translate "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!" %}</p>
        </div>

        <div class="sidebar-box">
          <h3 class="text-uppercase">{% translate "Remerciements" %}</h3>
          <p>{% translate "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!" %}</p>
        </div-->
      </div>
    </div>
  </div>
</div>

{% endblock body %}