core/urls.py
from django.urls import path, include
from core.views import ContactView, DetailNew, GalleryView, ContributorsView, NewsView

app_name = 'core'

urlpatterns = [
    path('gallery/', GalleryView.as_view(), name='gallery'),
    path('contributors/', ContributorsView.as_view(), name='contributors'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('news/', NewsView.as_view(), name='news'),
    path('news/<str:canonical_name>-<int:id>/',
         DetailNew.as_view(),
         name='post'),
]

football_competion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('tournoi.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

tournoi/urls.py
from django.urls import path
from tournoi.views import IndexView, MatchView, TeamView

app_name = 'tournoi'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('match/', MatchView.as_view(), name='match'),
    path('teams/', TeamView.as_view(), name='team'),
]

core/models.py
from django.db import models
from django_tuieditor.models import MarkdownField
from tournoi.models import Edition


class ContactInfo(models.Model):
    '''Manages the contact form/page'''
    name = models.CharField(
        max_length=150,
        null=False,
        blank=False,
        error_messages={'required': ("Veuillez entrer votre nom et prénom.")})
    email = models.EmailField(
        null=True,
        blank=True,
        error_messages={'required': ("Veuillez entrer votre adresse email.")})
    phone = models.CharField(max_length=9,
                             null=False,
                             blank=False,
                             error_messages={
                                 'required':
                                 ("Veuillez entrer votre numéro de téléphone.")
                             })
    subject = models.CharField(
        max_length=100,
        error_messages={
            'required': ("Veuillez entrer le titre de votre message.")
        })
    message = models.TextField(
        null=False,
        blank=False,
        error_messages={'required': ("Veuillez entrer votre message.")})

    def __str__(self):
        return self.name + ' ' + self.subject


class Author(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='author',
                              default='author/avatar.png',
                              null=True,
                              blank=True)
    description = MarkdownField(max_length=150, null=False, blank=False)

    def __str__(self) -> str:
        return self.name


class News(models.Model):
    image = models.ImageField(
        upload_to='actualites/',
        default="news_placeholder.jpg",
    )
    title = models.CharField(
        max_length=200,
        null=False,
        blank=False,
    )
    description = MarkdownField(
        null=False,
        blank=False,
    )
    edition = models.ForeignKey(Edition, models.CASCADE)
    add_on = models.DateField(auto_now=True)
    author = models.ForeignKey(Author, models.CASCADE)

    def __str__(self):
        return self.title


class Gallery(models.Model):
    title = models.CharField(max_length=300, blank=True, null=True)
    edition = models.ForeignKey(Edition,
                                models.CASCADE,
                                related_name='gallery',
                                null=True,
                                blank=True)

    def __str__(self) -> str:
        return self.title


class GalleryImage(models.Model):
    gallery = models.ForeignKey(Gallery, models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='galleries/', null=False)
    alt = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self) -> str:
        return f'photo de {self.gallery.title}'


class Contributor(models.Model):
    image = models.ImageField(upload_to='contributors/', null=False)
    name = models.CharField(max_length=300, blank=True, null=True)
    title = models.CharField(max_length=300, blank=True, null=True)
    website = models.URLField(max_length=300, )
    twitter = models.URLField(max_length=300, )
    github = models.URLField(max_length=300, )
    description = models.TextField()

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from .models import ContactInfo
from django.forms.widgets import CheckboxInput, EmailInput, FileInput, NumberInput, PasswordInput, Select, TextInput, Textarea


# Create your forms below.
class ContactForm(forms.ModelForm):
    # Meta data
    class Meta:
        model  = ContactInfo

        # Form fields
        fields = [
            'name',
            'email',
            'phone',
            'subject',
            'message'
        ]

        # Definition of widgets
        widgets = {
            'name': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Nom et Prénom',
                }
            ),

            'email': EmailInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Your email address',
                }
            ),

            'phone': TextInput(
                attrs={
                    'class': 'form-control w-75',
                    'placeholder': 'Téléphone (Ex. 699887755)',
                }
            ),

            'subject': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Message Subject...',
                }
            ),

            'message': Textarea(
                attrs={
                    'cols': '30',
                    'rows': '10',
                    'class': 'form-control',
                    'placeholder': 'Ecrivez votre message...',
                }
            ),
        }

core/views.py
from pipes import Template
from pprint import pp, pprint
from django.shortcuts import get_object_or_404, redirect, render, HttpResponse
from django.db.models import Count
from django.views import View
from core.models import Contributor, GalleryImage, News, Gallery
from django.views.generic import ListView
from .forms import ContactForm
from django.core.mail.message import BadHeaderError
from django.core.mail import send_mail
from django.contrib import messages
from django.utils.html import format_html
from tournoi.models import Edition
from django.views.generic import TemplateView


class ContactView(View):
    template_name = 'core/contact.html'
    form_class = ContactForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']

            # Additional fields
            messsage = f"\n\nNouveau message sur coupe.comsas.club : Emetteur: {name}\n\nAdresse: {email} Message:{message}"
            subjectEmail = f'{subject}From <{email}>'

            # Uncomment this later to send email to required address
            # try:
            #     send_mail(
            #         subjectEmail,  #subject
            #         message,  #message
            #         email,  #from email
            #             ,  #to email
            #     )
            # except BadHeaderError:
            #     message.error(request, 'Désolé, Nous avons rencontré un problème lors de l\'envoi de votre reponse. Veuillez réessayer plustard.')

            # Test if form data was saved and output corresponding flash message to confirm message placement or not.
            try:
                form.save()
                message_out_success = format_html(
                    # f'Thanks for contacting us, <strong> {name} </strong> ! Your message has been sent successfully. You will be email a copy at <strong> {email} </strong> !'
                    f'Votre message a été envoyé avec succès. Merci de nous avoir contacté,'
                )
                messages.success(request, message_out_success)
            except:
                messages.error(request, 'Désolé, Nous avons rencontré un problème lors de l\'envoi de votre reponse. Veuillez réessayer plustard.')

            # Redidrect to the same page with message output.
            return redirect('core:contact')
        else:
            return render(request, self.template_name, {'form': form})


class GalleryView(View):
    template_name = "core/gallery.html"

    def get(self, request, *args, **kwargs):
        last_edition = Edition.objects.filter(
            status='programmed').order_by('-end_date').first()
        last_edition_gallery = Gallery.objects.filter(
            edition=last_edition.id).first()
        last_edition_images = GalleryImage.objects.filter(
            gallery=last_edition_gallery.id)
        context = {
            'last_edition_images': last_edition_images,
        }
        return render(request, self.template_name, context)


class ContributorsView(ListView):
    template_name = "core/contributors.html"
    queryset = Contributor.objects.all()


class NewsView(View):
    template_name = "core/blog.html"

    def get(self, request, *args, **kwargs):
        queryset = News.objects.filter(edition__status='active')
        context = {'news': queryset}
        return render(request, self.template_name, context)


class DetailNew(View):
    template_name = "core/single.html"

    def get(self, request, *args, **kwargs):
        new = get_object_or_404(News, id=self.kwargs['id'])
        news = News.objects.filter(edition__status='active')
        context = {'new': new, 'news': news}
        return render(request, self.template_name, context)

core/templates/contact.html
{% extends 'main.html' %}
{% load static %}
{% load i18n %}

<!-- Page Title-->
{% block title %}
  {% translate "Coupe du département Informatique" %} &dash; {% translate "Contacts" %}
{% endblock title %}

<!-- Page Body -->
{% block body %}
<div class="hero overlay" style="background-image: url('../../static/images/contact.jpg');">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-9 mx-auto text-center">
        <h1 class="text-white">{% translate "Contactez Nous" %}</h1>
        <p>
          {% translate "Pour tous vos soucis, suggestions, question et imcomprehensions durant ce 
          championnat veuillez remplir le formulaire suivant pour nous laisser un message, 
          ou alors contactez-nous directement." %}
        </p>
        {% comment %} Output message according to criteria {% endcomment %}
        {% for msg in messages %}
          <div class="alert alert-{%if msg.level_tag == error %}danger{% else %}{{msg.level_tag}}{% endif %} alert-dismissible fade show" role="alert">
          <i class="bi bi-{%if msg.level_tag == error %}exclamation-octagon-fill{% elif msg.level_tag == info %}info-circle-fill{% elif msg.level_tag == warning %}exclamation-triangle-fill{% else %}check-circle-fill{% endif %}"></i>  
            {% blocktrans %} {{msg}} {% endblocktrans %}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>


<div class="site-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-7">
        <form action="{% url 'core:contact' %}" method="POST" role="form">
          {% csrf_token %}
          <div class="form-group">
            {% blocktrans %} {{modelform.name}} {% endblocktrans %}
          </div>
          <div class="form-group d-flex">
            {% blocktrans %} {{modelform.email}} {% endblocktrans %}
            &ThickSpace;
            {% blocktrans %} {{modelform.phone}} {% endblocktrans %}
          </div>
          <div class="form-group">
            {% blocktrans %} {{modelform.subject}} {% endblocktrans %}
          </div>
          <div class="form-group">
            {% blocktrans %} {{modelform.message}} {% endblocktrans %}
          </div>
          <div class="form-group">
            <input type="submit" class="btn btn-primary py-3 px-5" value="Envoyer">
          </div>
        </form>  
      </div>
      <div class="col-lg-4 ml-auto">
        
        <ul class="list-unstyled">
          <li class="mb-2">
            <strong class="text-white d-block">Email</strong>
            <a href="mailto: info@comsas.club">info@comsas.club</a>
          </li>
          <li class="mb-2">
            <strong class="text-white d-block">
              {% translate "Téléphone" %}
            </strong>
            <a href="#">+(237) 699016727 / 658085308</a>
          </li>
          <li class="mb-2">
            <strong class="text-white d-block">Adresse</strong>
            Derrière l'Amphi 502 <br> Yaoundé, Cameroon
          </li>
        </ul>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3980.779097126594!2d11.496744414841578!3d3.8575241494649335!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x108bcfbcd74786bb%3A0x1c3486b01dabee36!2scomsas!5e0!3m2!1sen!2scm!4v1648149854296!5m2!1sen!2scm" width="100%" height="280" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

core/templates/contributors.html
{% extends 'main.html' %}
{% load static %}
{% load i18n %}

<!-- Block Title -->
{% block title %}
    {% translate "Coupe du département Informatique" %} &dash; {% translate "Contributeurs" %}
{% endblock title %}

<!-- Page Body -->
{% block body %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-center align-items-center" style="background-image: url('../../static/images/gallery-bg.webp');">
    <div class="hero-container" data-aos="fade-in">
      <h1><span style="color: transparent; -webkit-text-stroke-width: 2px; -webkit-text-stroke-color: #ee1e46;">#</span> La T<span style="color: #ee1e46; border-bottom: 5px solid #ee1e46;">e</span>ch <span style="color: #ee1e46;"><\</span>Team<span style="color: #ee1e46;">></span></h1><span style="color: #ee1e46;"></span>
      <br>
      <small>
          {% translate "Nous l'avons essayé, et nous l'avons réalisé." %}
        </small>
      <br>
    </div>
</section>
<!-- End Hero -->

<br>
<br>

<!-- Contributor Section Begin -->
<section class="speaker-section spad">
    <div class="container">
        <div class="row">
            {% for person in contributors %}
            <div class="col-md-6">
                <div class="speaker-item">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="si-pic">
                                <img src=" {{person.image}} " alt="{{person.name}}">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="si-text text-capitalize">
                                <div class="si-title">
                                    <h4>{{person.name}}</h4>
                                    <span class="text-capitalize">
                                        {% blocktrans %} {{person.title}} {% endblocktrans %}
                                    </span>
                                </div>
                                <div class="si-social">
                                    <a href="{{person.website}}"><i class="bi bi-globe2"></i></a>
                                    <a href="{{person.twitter}}"><i class="bi bi-twitter"></i></a>
                                    <a href="{{person.github}}"><i class="bi bi-github"></i></a>
                                </div>
                                <p>
                                    {% blocktrans %} {{person.description}} {% endblocktrans %}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Contributor Section End -->
    
{% endblock body %}

core/templates/index.html
{% extends 'main.html' %}

<!-- load some element -->
{% load static %}
{% load i18n %}
{% load gfm%}

<!-- Title of home the page-->
{% block title %}
  {% translate "Coupe du département Informatique" %} &dash; {% translate "Accueil" %}
{% endblock title %}


<!-- Body of the home page-->
{% block body %}
<div class="hero overlay" style="background-image: url('../../static/images/bg_3.jpg');">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-5 ml-auto">
        <h1 class="text-white">Coupe du Département <span style="color: #ee1e46;">Info</span><span style="color: transparent; -webkit-text-stroke-width: 2px; -webkit-text-stroke-color: #fff;">rmatique</span></h1>
        <p>
          {% translate "Ce n'est pas toujours une affaire de machines. On s'y connait aussi au foot. Encore ... " %}
        </p>
        <div id="date-countdown"></div>
        <p>
          {% translate "Jusqu'au lancement officiel du championnat." %}
        </p>
        <p>
          <a href="#latest-news" class="btn btn-primary py-3 px-4 mr-3">{% translate "Découverte" %}</a>
          <a href="{% url 'core:match' %}" class="btn more light">{% translate "Statistiques" %}</a>
        </p>  
      </div>
    </div>
  </div>
</div>



<div class="container">
  

  <div class="row">
    <div class="col-lg-12">
      {% if last_match %}
        <div class="d-flex team-vs">
          <span class="score">{{ match.goal_team1}} : {{ match.goal_team2 }}</span>
          <div class="team-1 w-50">
            <div class="team-details w-100 text-center">
              <img src=" {{last_match.team1.logo.url}} " alt="Image" class="img-fluid">
              <h3 class="text-uppercase">{{last_match.team1.name}} {% if last.macth.winner == last_match.team1 %} <small style="color: #ee1e46; font-weight: 600;">({% translate "victoire" %})</small> <i class="bi bi-hand-thumbs-up-fill"></i>
                {% elif  last.macth.winner == last_match.team2 %}<small style="color: #000; font-weight: 600;">({% translate "défaite" %})</small>{% endif %} </h3>
              <ul class="list-unstyled">

              </ul>
            </div>
          </div>
          <div class="team-2 w-50">
            <div class="team-details w-100 text-center">
              <img src=" {{last_match.team2.logo.url}} " alt="Image" class="img-fluid">
              <h3 class="text-uppercase">{{last_match.team2.name}} {% if last.macth.winner == last_match.team2 %} <small style="color: #ee1e46; font-weight: 600;">({% translate "victoire" %})</small> <i class="bi bi-hand-thumbs-up-fill"></i>
                {% elif  last.macth.winner == last_match.team1 %}<small style="color: #000; font-weight: 600;">({% translate "défaite" %})</small>{% endif %}</h3>
              
            </div>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
</div>


<div class="latest-news">
  <div class="container">
    <div class="row">
      <div class="col-12 title-section">
        <h2 class="heading" id="latest-news">{% translate "Actualités sur le championnat" %}</h2>
      </div>
    </div>
    <div class="row no-gutters">

      {% for actu in news %}
      <div class="col-md-4">
        <div class="post-entry">
          <a href="#">
            <img src=" {{actu.image}} " alt="Image" class="img-fluid">
          </a>
          <div class="caption">
            <div class="caption-inner">
              <h3 class="mb-3 text-capitalize">{{actu.title|title}}</h3>
              <p style="color: #e2e2e2;">
                {{actu.description|gfm}}
              </p>
            </div>
          </div> 
        </div>
      </div>
      {% endfor %}

    </div>

  </div>
</div>

<div class="site-section bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="widget-next-match">
          <div class="widget-title">
            <h3 class="text-capitalize">{% translate "Prochain Match" %}</h3>
          </div>
          <div class="widget-body mb-3">
            <div class="widget-vs">
              <div class="d-flex align-items-center justify-content-around justify-content-between w-100">
                <div class="team-1 text-center">
                  <img src=" {{next_match.team1.logo.url}} " alt="{{next_match.team1.name}}">
                  <h3 class="text-capitalize">{{next_match.team1.name}}</h3>
                </div>
                <div>
                  <span class="vs"><span>VS</span></span>
                </div>
                <div class="team-2 text-center">
                  <img src=" {{next_match.team2.logo.url}} " alt="{{next_match.team2.name}}">
                  <h3 class="text-capitalize">{{next_match.team2.name}}</h3>
                </div>
              </div>
            </div>
          </div>

          <div class="text-center widget-vs-contents mb-4">
            <h4 class="text-capitalize">{% translate "Coupe du département" %}</h4>
            <p class="mb-5">
              <span class="d-block">{{ next_match.date_to_play }}</span>
              <!-- span class="d-block">15:30 (GMT+1)</span   !-->
              <strong class="text-primary">Stade Mateco</strong>
            </p>

            <div id="date-countdown2" class="pb-1"></div>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        
        <div class="widget-next-match">
          <table class="table custom-table">
            <thead>
              <tr>
                {% comment %} 
                  Normalement la traduction en anglais devrait aussi changer les lettres ci dessous comme suit.
                  Fr ------ En
                  R  =====> R
                  J  =====> P
                  V  =====> W
                  N  =====> D
                  D  =====> L
                  PTS  =====> PTS
                {% endcomment %}

                <th>R</th>
                <th>{% translate "Équipe" %}</th>
                <th>J</th>
                <th>V</th>
                <th>N</th>
                <th>D</th>
                <th>PTS</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>1</td>
                <td><strong class="text-white">{# Nom de l'equipe #}</strong></td>
                <td>2</td>
                <td>22</td>
                <td>3</td>
                <td>2</td>
                <td>140</td>
              </tr>
              <tr>
                <td>2</td>
                <td><strong class="text-white">{# Nom de l'equipe #}</strong></td>
                <td>2</td>
                <td>22</td>
                <td>3</td>
                <td>2</td>
                <td>140</td>
              </tr>
              <tr>
                <td>3</td>
                <td><strong class="text-white">{# Nom de l'equipe #}</strong></td>
                <td>2</td>
                <td>22</td>
                <td>3</td>
                <td>2</td>
                <td>140</td>
              </tr>
              <tr>
                <td>4</td>
                <td><strong class="text-white">{# Nom de l'equipe #}</strong></td>
                <td>2</td>
                <td>22</td>
                <td>3</td>
                <td>2</td>
                <td>140</td>
                
              </tr>
              <tr>
                <td>5</td>
                <td><strong class="text-white">{# Nom de l'equipe #}</strong></td>
                <td>2</td>
                <td>22</td>
                <td>3</td>
                <td>2</td>
                <td>140</td>
              </tr>
              <tr style="background-color: #751d2e;">
                <td>6</td>
                <td><strong class="text-white">{# Nom de l'equipe #}</strong></td>
                <td>2</td>
                <td>22</td>
                <td>3</td>
                <td>2</td>
                <td>140</td>
              </tr>
              <tr style="background-color: #751d2e;">
                <td>7</td>
                <td><strong class="text-white">{# Nom de l'equipe #}</strong></td>
                <td>2</td>
                <td>22</td>
                <td>3</td>
                <td>2</td>
                <td>140</td>
              </tr>
              <tr style="background-color: #751d2e;">
                <td>8</td>
                <td><strong class="text-white">{# Nom de l'equipe #}</strong></td>
                <td>2</td>
                <td>22</td>
                <td>3</td>
                <td>2</td>
                <td>140</td>
              </tr>
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>
</div> <!-- .site-section -->

<div class="site-section">
  <div class="container">
    <div class="row">
      <div class="col-6 title-section">
        <h2 class="heading text-capitalize">{% translate "Vidéos | Temps Forts" %}</h2>
      </div>
      <div class="col-6 text-right">
        <div class="custom-nav">
        <a href="#" class="js-custom-prev-v2"><span class="icon-keyboard_arrow_left"></span></a>
        <span></span>
        <a href="#" class="js-custom-next-v2"><span class="icon-keyboard_arrow_right"></span></a>
        </div>
      </div>
    </div>


    <div class="owl-4-slider owl-carousel">
      <div class="item">
        <div class="video-media">
          <img src=" {% static 'images/img_1.jpg' %} " alt="Image" class="img-fluid">
          <a href="" class="d-flex play-button align-items-center" data-fancybox>
            <span class="icon mr-3">
              <span class="icon-play"></span>
            </span>
            <div class="caption">
              <h3 class="m-0">Dogba set for Juvendu return?</h3>
            </div>
          </a>
        </div>
      </div>
      <div class="item">
        <div class="video-media">
          <img src=" {% static 'images/img_2.jpg' %} " alt="Image" class="img-fluid">
          <a href="" class="d-flex play-button align-items-center" data-fancybox>
            <span class="icon mr-3">
              <span class="icon-play"></span>
            </span>
            <div class="caption">
              <h3 class="m-0">Kai Nets Double To Secure Comfortable Away Win</h3>
            </div>
          </a>
        </div>
      </div>
      <div class="item">
        <div class="video-media">
          <img src=" {% static 'images/img_3.jpg' %} " alt="Image" class="img-fluid">
          <a href="" class="d-flex play-button align-items-center" data-fancybox>
            <span class="icon mr-3">
              <span class="icon-play"></span>
            </span>
            <div class="caption">
              <h3 class="m-0">Romolu to stay at Real Nadrid?</h3>
            </div>
          </a>
        </div>
      </div>

      <div class="item">
        <div class="video-media">
          <img src=" {% static 'images/img_1.jpg' %} " alt="Image" class="img-fluid">
          <a href="" class="d-flex play-button align-items-center" data-fancybox>
            <span class="icon mr-3">
              <span class="icon-play"></span>
            </span>
            <div class="caption">
              <h3 class="m-0">Dogba set for Juvendu return?</h3>
            </div>
          </a>
        </div>
      </div>
      <div class="item">
        <div class="video-media">
          <img src=" {% static 'images/img_2.jpg' %} " alt="Image" class="img-fluid">
          <a href="" class="d-flex play-button align-items-center" data-fancybox>
            <span class="icon mr-3">
              <span class="icon-play"></span>
            </span>
            <div class="caption">
              <h3 class="m-0">Kai Nets Double To Secure Comfortable Away Win</h3>
            </div>
          </a>
        </div>
      </div>
      <div class="item">
        <div class="video-media">
          <img src=" {% static 'images/img_3.jpg' %} " alt="Image" class="img-fluid">
          <a href="" class="d-flex play-button align-items-center" data-fancybox>
            <span class="icon mr-3">
              <span class="icon-play"></span>
            </span>
            <div class="caption">
              <h3 class="m-0">Romolu to stay at Real Nadrid?</h3>
            </div>
          </a>
        </div>
      </div>

    </div>

  </div>
</div>

{% comment %} <div class="container site-section">
  <div class="row">
    <div class="col-6 title-section">
      <h2 class="heading">Blog</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6">
      <div class="custom-media d-flex">
        <div class="img mr-4">
          <img src=" {% static 'images/img_1.jpg' %} " alt="Image" class="img-fluid">
        </div>
        <div class="text">
          <span class="meta">May 20, 2020</span>
          <h3 class="mb-4"><a href="#">Romolu to stay at Real Nadrid?</a></h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus deserunt saepe tempora dolorem.</p>
          <p><a href="#">Read more</a></p>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="custom-media d-flex">
        <div class="img mr-4">
          <img src=" {% static 'images/img_3.jpg' %} " alt="Image" class="img-fluid">
        </div>
        <div class="text">
          <span class="meta">May 20, 2020</span>
          <h3 class="mb-4"><a href="#">Romolu to stay at Real Nadrid?</a></h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus deserunt saepe tempora dolorem.</p>
          <p><a href="#">Read more</a></p>
        </div>
      </div>
    </div>
  </div>
</div> {% endcomment %}

{% endblock body %}